### ISSUE TITLE
Unable to loop through array using for-statement

### ISSUE THREAD

**Issue by Highly-Unstable-Hadron** [Venger-King/WaveGrass#15]
I'm trying to print each element (separated by a comma) in an array using a for-loop, but it throws an error.

Code (the whole thing):
```
a = [2, "string", true, null]

for char in a{
    print(char, end:", ", colored: true)
}
```

Error:
```
--------\WaveGrass-0.1.1-beta\execute.js:897
            let iterator = iteratable.__iterator__()
                                      ^

TypeError: iteratable.__iterator__ is not a function
    at run (--------\WaveGrass-0.1.1-beta\execute.js:897:39)
←[90m    at processTicksAndRejections (node:internal/process/task_queues:96:5)←[39m
    at async execute (--------\WaveGrass-0.1.1-beta\execute.js:1043:9)
    at async parse (--------\WaveGrass-0.1.1-beta\parser.js:665:5)
    at async lex (--------\WaveGrass-0.1.1-beta\lexer.js:389:5)
    at async run (--------\WaveGrass-0.1.1-beta\main.js:36:34)

Node.js v17.8.0
```

I'm running this using WaveGrass v0.1.1 Beta source code.

**Comment by Venger-King** [comment]
fixed in v0.1.1-stable
